export type TaskErrorCode =
  | "AUTHORIZED_DIRECTORY_INVALID"
  | "AUTHORIZED_DIRECTORY_NOT_FOUND"
  | "AUTHORIZED_DIRECTORY_SNAPSHOT_STALE"
  | "CLAUDE_HISTORY_UNAVAILABLE"
  | "CLAUDE_SESSION_CONFLICT"
  | "CLAUDE_SESSION_NOT_FOUND"
  | "CODEX_APP_SERVER_UNAVAILABLE"
  | "CODEX_HISTORY_UNAVAILABLE"
  | "CODEX_REQUEST_NOT_ALLOWED"
  | "CODEX_THREAD_NOT_FOUND"
  | "CONCURRENT_TASK_LIMIT_REACHED"
  | "INVALID_TASK_OPERATION"
  | "HISTORY_CURSOR_STALE"
  | "STALE_APPROVAL"
  | "TASK_BUSY"
  | "TASK_CONTROL_NOT_SUPPORTED"
  | "TASK_INTERRUPTED"
  | "TASK_NOT_FOUND"
  | "TASK_OPERATION_SUPERSEDED"
  | "TASK_SESSION_UNAVAILABLE"
  | "TASK_TERMINAL"
  | "UNSUPPORTED_PERMISSION_MODE"
  | "VOLUME_ROOT_RISK_NOT_ACCEPTED"
  | "WORKSPACE_NOT_AUTHORIZED"
  | "WORKSPACE_SCOPE_RISK_NOT_ACCEPTED";

export class TaskError extends Error {
  public constructor(
    public readonly code: TaskErrorCode,
    public readonly statusCode: 403 | 404 | 409 | 422,
    message: string,
  ) {
    super(message);
    this.name = "TaskError";
  }
}
